spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytest
    username: root
    password: root


mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
#  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: cn.vic.init.bean

logging:
  level:
    root: WARN # 控制台日志只打印 WARN 级别的
    cn.vic.init.mapper.*: debug # mybatis 打印 SQL 语句



